select * where {
?s3 <http://prelex.publicdata.eu/ontology/directory_code> "11.70.20.20"@en .
?s4 <http://prelex.publicdata.eu/ontology/directory_code> "11.70.40.20"@en .
?s3 <http://prelex.publicdata.eu/ontology/com_number> ?cn .
?s4 <http://prelex.publicdata.eu/ontology/com_number> ?cn .
?s5 <http://prelex.publicdata.eu/ontology/directory_code> "11.40.10.30"@en .
?s5 <http://prelex.publicdata.eu/ontology/com_number> ?cn .
}