select * where {
?s5 <http://prelex.publicdata.eu/ontology/directory_code> "03.70.30.00"@en.
?s5 <http://prelex.publicdata.eu/ontology/adoption_commission> ?ad5 .
?s5 <http://purl.org/dc/terms/title> ?t5.
}