select ?d where {
?d <http://bio2rdf.org/drugbank_vocabulary:category> 'Dietary supplement'. 
?d <http://bio2rdf.org/drugbank_vocabulary:category> 'Nutraceutical'.
?d <http://bio2rdf.org/drugbank_vocabulary:category> 'Small molecule'.
}
ORDER BY ?d
LIMIT 10
OFFSET 10

