select * where {
?s2 <http://bio2rdf.org/interpro_vocabulary:example-entry> <http://bio2rdf.org/uniprot:P19793> .
?s3 <http://bio2rdf.org/interpro_vocabulary:example-entry> <http://bio2rdf.org/uniprot:P28700> .
?s2 <http://bio2rdf.org/interpro_vocabulary:taxon-distribution> ?d.
?s3 <http://bio2rdf.org/interpro_vocabulary:taxon-distribution> ?d.
?s3 <http://bio2rdf.org/interpro_vocabulary:x-cath> ?xc3.
}