select * where {
?p <http://dbpedia.org/property/associatedActs> <http://dbpedia.org/resource/Enrique_Iglesias>.
?p <http://dbpedia.org/ontology/associatedBand> ?bm1.
?p <http://dbpedia.org/ontology/associatedMusicalArtist> ?cm1.
?bm1 <http://dbpedia.org/property/instrument> ?in1.
?bm1 <http://dbpedia.org/property/associatedActs> ?act1.
?cm1 <http://dbpedia.org/property/instrument> ?in2.
?cm1 <http://dbpedia.org/property/associatedActs> ?act2.}
