select * where {
?s1 <http://www.w3.org/2004/02/skos/core#closeMatch> <http://id.loc.gov/authorities/sh85011804#concept>.
?s2 <http://www.w3.org/2004/02/skos/core#closeMatch> <http://d-nb.info/gnd/4144029-8>.
?s3 <http://www.w3.org/2004/02/skos/core#closeMatch> <http://data.bnf.fr/ark:/12148/cb12266268n>.
?s1 <http://www.w3.org/2004/02/skos/core#altLabel> ?l.
?s2 <http://www.w3.org/2004/02/skos/core#altLabel> ?l.
?s3 <http://www.w3.org/2004/02/skos/core#altLabel> ?l.
}
