select * where {
?s1 <http://www.w3.org/2004/02/skos/core#closeMatch> <http://lemac.sgcb.mcu.es/Autoridades/LEMAC201205299/concept>.
?s1 <http://www.w3.org/2004/02/skos/core#altLabel> ?l.
?s1 <http://purl.org/dc/terms/created> ?c1.
}