select * where {
?d1 <http://bio2rdf.org/drugbank_vocabulary:category> 'Antibiotics, Antifungal'. 
?d1 <http://bio2rdf.org/drugbank_vocabulary:ddi-interactor-in> ?i1.
?d1 <http://bio2rdf.org/drugbank_vocabulary:indication> ?i1.
?d1 <http://bio2rdf.org/drugbank_vocabulary:target> ?b.
?d1 <http://bio2rdf.org/drugbank_vocabulary:synonym> ?s1. 
}
