select * where {
?s1 <http://www.openlinksw.com/schemas/xbrl/role> "http://xbrl.iasb.org/int/fr/ifrs/gp/role/ExplanatoryDisclosures".
?s1 <http://www.openlinksw.com/schemas/xbrl/order> ?o.
?s1 <http://www.openlinksw.com/schemas/xbrl/weight> ?w1.
?s1 <http://www.openlinksw.com/schemas/xbrl/to> ?t1 .
?s1 <http://www.openlinksw.com/schemas/xbrl/from> ?f1 .
?s1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?pl1 .}
