select distinct ?o
where {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/AntineoplasticDrugs>.
?d1 <http://dbpedia.org/ontology/atcPrefix> ?o.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Immunosuppressants>.
?d2 <http://dbpedia.org/ontology/atcPrefix> ?o.
} 