select * where {
?s1 <http://bio2rdf.org/pubmed_vocabulary:suppl_mesh_heading> <http://bio2rdf.org/pubmed_resource:19648123SUPPL_MESH_HEADING_2>.
?s1 <http://bio2rdf.org/pubmed_vocabulary:author> ?o.
?s1 <http://bio2rdf.org/pubmed_vocabulary:affiliation> ?a.
?s1 <http://purl.org/dc/terms/abstract> ?a1.
}
