select * where {
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/region> ?o1.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/region> ?o2.
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/282#this>.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/478#this>.
}
