select * where {
?s1 <http://bio2rdf.org/hhpid_vocabulary:elementGene2> ?e.
?s2 <http://bio2rdf.org/hhpid_vocabulary:elementGene2> ?e.
?s3 <http://bio2rdf.org/hhpid_vocabulary:elementGene2> ?e.
?s1 <http://bio2rdf.org/hhpid_vocabulary:keyword> 'binds' .
?s2 <http://bio2rdf.org/hhpid_vocabulary:keyword> 'inhibits' .
?s3 <http://bio2rdf.org/hhpid_vocabulary:keyword> 'recruits' .
}