select * where {
?s1 <http://bio2rdf.org/hhpid_vocabulary:elementGene2> ?e1.
?s1 <http://bio2rdf.org/hhpid_vocabulary:keyword> ?k .
?s1 <http://bio2rdf.org/hhpid_vocabulary:relatedPublication> ?rp1.
?s1 <http://bio2rdf.org/hhpid_vocabulary:elementProteinVersion1> ?p1.
?s1 <http://bio2rdf.org/hhpid_vocabulary:interactionDesc> ?id1 .
?s1 <http://bio2rdf.org/hhpid_vocabulary:elementProteinVersion2> <http://bio2rdf.org/ncbi:NP_006254.1> .
}