select * where {
?s6 <http://www.w3.org/ns/dcat#keyword> "format-sioc" .
?s6 <http://www.w3.org/ns/dcat#distribution> ?d .
?s6 <http://xmlns.com/foaf/0.1/homepage> ?h6.
?s6 <http://purl.org/dc/terms/relation> ?r6 .
?s7 <http://www.w3.org/ns/dcat#distribution> ?d .
}
