select distinct ?up where {
{?s1 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> <http://bio2rdf.org/taxon:4129> .
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> <http://bio2rdf.org/taxon:2771> .
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-gi> ?xg1 .
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-gi> ?xg2 .
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr1.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr2.
?s1 <http://bio2rdf.org/iproclass_vocabulary:x-uniparc> ?up.
?s2 <http://bio2rdf.org/iproclass_vocabulary:x-uniparc> ?up.
}
UNION
{?s3 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> <http://bio2rdf.org/taxon:65393> .
 ?s4 <http://bio2rdf.org/iproclass_vocabulary:x-taxon> <http://bio2rdf.org/taxon:41431> .
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-genbank> ?g4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-uniprot> ?xu3 .
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-uniprot> ?xu4 .
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-geneid> ?gn4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr3.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-refseq> ?xr4.
?s3 <http://bio2rdf.org/iproclass_vocabulary:x-uniparc> ?up.
?s4 <http://bio2rdf.org/iproclass_vocabulary:x-uniparc> ?up.
}
}