select distinct ?cn where {
?s1 <http://prelex.publicdata.eu/ontology/directory_code> "06.20.20.10"@en.
?s2 <http://prelex.publicdata.eu/ontology/directory_code> "06.20.20.25"@en.
?s1 <http://prelex.publicdata.eu/ontology/com_number> ?cn .
?s2 <http://prelex.publicdata.eu/ontology/com_number> ?cn .
?s1 <http://prelex.publicdata.eu/ontology/doc_id> ?did1 .
?s2 <http://prelex.publicdata.eu/ontology/doc_id> ?did2 .
?s1 <http://prelex.publicdata.eu/ontology/event> ?e1 .
?s2 <http://prelex.publicdata.eu/ontology/event> ?e2 .
?s1 <http://prelex.publicdata.eu/ontology/perma_url> ?pu1 .
?s2 <http://prelex.publicdata.eu/ontology/perma_url> ?pu2 .
?s1 <http://prelex.publicdata.eu/ontology/adoption_commission> ?ad1 .
?s2 <http://prelex.publicdata.eu/ontology/adoption_commission> ?ad2 .
?s1 <http://purl.org/dc/terms/title> ?t1 .
?s2 <http://purl.org/dc/terms/title> ?t2 .
}
