select distinct ?t where {
{
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/religion> ?t.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/religion> ?t.
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/272#this>.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/92#this>.
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/aboriginalpopulation> ?ap1.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/aboriginalpopulation> ?ap2.
}
UNION
{
?s3 <http://lod.apc.gov.tw:8890/schemas/Contest/religion> ?t.
?s4 <http://lod.apc.gov.tw:8890/schemas/Contest/religion> ?t.
?s3 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/514#this>.
?s4 <http://lod.apc.gov.tw:8890/schemas/Contest/ethnic_of> <http://lod.apc.gov.tw:8890/Contest/tribeapproved/ID/490#this>.
?s3 <http://lod.apc.gov.tw:8890/schemas/Contest/aboriginalpopulation> ?ap3.
?s4 <http://lod.apc.gov.tw:8890/schemas/Contest/aboriginalpopulation> ?ap4.
}
}