select distinct ?o1 where {
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/id> '33' .
?s1 <http://lod.apc.gov.tw:8890/schemas/Contest/neighborhood> ?o1.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/neighborhood> ?o1.
?s2 <http://lod.apc.gov.tw:8890/schemas/Contest/id> '1' .
?s3 <http://lod.apc.gov.tw:8890/schemas/Contest/id> '452' .
?s4 <http://lod.apc.gov.tw:8890/schemas/Contest/neighborhood> ?o1.
?s3 <http://lod.apc.gov.tw:8890/schemas/Contest/neighborhood> ?o1.
?s4 <http://lod.apc.gov.tw:8890/schemas/Contest/id>  '203'.
}